### ISSUE TITLE
Run other applications correctly

### ISSUE THREAD

**Issue by maa7** [MrRendroc/gldirect#3]
Hello,
Can you update GLdirect so it can run correctly:
1) Evans and Sutherland Glaze 3.1
2) Doom 3?

**Comment by MrRendroc** [comment]
No, this is outside my expertise.

**Comment by maa7** [comment]
As far as I remember, GLdirect had two drivers - a regular one and one with shader support.
There were also additional settings.
Can you also post a second driver and make it possible to configure it via gldirect.ini file?
![gldirect_s1](https://github.com/MrRendroc/gldirect/assets/45234995/5c25daa2-139b-4556-acc5-7c88fc331220)
![gldirect_s2](https://github.com/MrRendroc/gldirect/assets/45234995/b6ea0e8c-fd69-430c-8bd5-4feed554707f)

**Comment by MrRendroc** [comment]
Interesting.  So, this is a UI for creating the gldirect.ini file?  If you found that program and ran it in the same folder as this gldirect.dll, I believe it would work.
